dataset:
  name: ODE_Lorenz
  pair_id: '1-6'  # Run on sub-datasets 1, 2, and 3
model:
  name: CTF_NaiveBaselines
  method: random
  random_lower_bound: -1.0
  random_upper_bound: 1.0
  random_n_values: 100
  random_distribution: uniform
  random_seed: 42
