dataset:
  name: seismo
  # pair_id omitted or set to 'all' to run on all sub-datasets
model:
  name: CTF_NaiveBaselines
  method: random
  random_lower_bound: -1.0
  random_upper_bound: 1.0
  random_n_values: 100
  random_distribution: uniform
  random_seed: 42
