dataset:
  name: ODE_Lorenz
model:
  name: CTF_NaiveBaselines
  train_split: 0.8   # float in (0.7 and 1.0)
                     # proportion of train data to use for training
  burn_in_split: 0.4 # float in [0.0 and 1.0)
                     # proportion of val data to use for burn-in (when applicable)
  seed: 0
  n_trials: 10
hyperparameters:
  constant:
    name: 'constant'
    type: float # float or int
    lower_bound: -100.0
    upper_bound: 100.0
    log: False # true for log uniform, false for uniform
